USE [THITRACNGHIEM]
GO
/****** Object:  StoredProcedure [dbo].[SP_BAITHI_LAYTHOIGIAN]    Script Date: 6/29/2026 10:12:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_BAITHI_LAYTHOIGIAN]
    @MASV nChar(8), @MAMH nChar(5), @LAN smallint
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP 1 THOIGIAN_CONLAI FROM BAITHI_TAM
    WHERE MASV=@MASV AND MAMH=@MAMH AND LAN=@LAN;
END